apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-6p-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sit323-6p-app
  template:
    metadata:
      labels:
        app: sit323-6p-app
    spec:
      containers:
      - name: sit323-6p-app
        image: agrimgautam/sit323-6p-app:v1
        ports:
        - containerPort: 8080